services:
  - type: web
    name: empower-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn return_to_work.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,empower-pi.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: empower-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://empower-pi.vercel.app

databases:
  - name: empower-db
    databaseName: empower
    plan: free