# Generated by Django 5.1.5 on 2025-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pinned', models.BooleanField(default=False)),
                ('upvotes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
