# Generated by Django 5.1.5 on 2025-03-08 20:18
from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0001_initial'),
    ]

    operations = [
            migrations.AddField(
            model_name='task',
            name='quiz_type',
            field=models.CharField(
                choices=[
                    ('flashcard', 'Flashcard Quiz'),
                    ('statement_sequence', 'Statement Sequence Quiz'),
                    ('text_input', 'Text Input Quiz'),
                    ('question_answer_form', 'Question Answer Form'),
                    ('matching_questions', 'Matching Question Quiz')
                ],
                default='text_input',
                max_length=30,
                null=True  # Use null=True if this field wasn't required initially
            ),
        ),
    ]
