# Generated by Django 5.1.5 on 2025-03-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='quiz_type',
            field=models.CharField(choices=[('flashcard', 'Flashcard Quiz'), ('statement_sequence', 'Statement Sequence Quiz'), ('text_input', 'Text Input Quiz'), ('question_input', 'Question Answer Form'), ('pair_input', 'Matching Question Quiz')], default='text_input', max_length=30),
        ),
    ]
