# Generated by Django 5.1.5 on 2025-03-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='pinned',
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='hasLiked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
