# Generated by Django 5.1.5 on 2025-03-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='question_audio/'),
        ),
    ]
