# Generated by Django 5.1.5 on 2025-04-05 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0002_remove_audioclip_question_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embeddedvideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Embedded Video', 'verbose_name_plural': 'Embedded Videos'},
        ),
        migrations.AddField(
            model_name='embeddedvideo',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='quiz_type',
            field=models.CharField(choices=[('flashcard', 'Flashcard Quiz'), ('statement_sequence', 'Statement Sequence Quiz'), ('text_input', 'Text Input Quiz'), ('question_input', 'Question Answer Form'), ('pair_input', 'Matching Question Quiz'), ('ranking_quiz', 'Ranking Quiz')], default='text_input', max_length=30),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('contentID', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('file_url', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('file_size_formatted', models.CharField(blank=True, max_length=20, null=True)),
                ('file_type', models.CharField(max_length=10)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_author_contents', to=settings.AUTH_USER_MODEL)),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_contents', to='returnToWork.module')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
