# Generated by Django 5.1.5 on 2025-03-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0002_alter_task_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
