# Generated by Django 5.1.5 on 2025-02-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0002_module_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='tags_for_module', to='returnToWork.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='modules_for_tag', to='returnToWork.tags'),
        ),
    ]
