# Generated by Django 5.1.5 on 2025-04-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0003_alter_embeddedvideo_options_embeddedvideo_video_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclip',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='embeddedvideo',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infosheet',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inlinepicture',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rankingquestion',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
    ]
