# Generated by Django 5.1.5 on 2025-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0003_questionanswerform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='quiz_type',
            field=models.CharField(choices=[('flashcard', 'Flashcard Quiz'), ('statement_sequence', 'Statement Sequence Quiz'), ('text_input', 'Text Input Quiz'), ('question_answer_form', 'Question Answer Form')], default='text_input', max_length=30),
        ),
    ]
