# Generated by Django 5.1.5 on 2025-03-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0003_quizquestion_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswerform',
            name='author',
        ),
        migrations.RemoveField(
            model_name='questionanswerform',
            name='moduleID',
        ),
        migrations.DeleteModel(
            name='MatchingQuestionQuiz',
        ),
        migrations.DeleteModel(
            name='QuestionAnswerForm',
        ),
    ]
