# Generated by Django 5.1.5 on 2025-03-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0003_usermoduleinteraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermoduleinteraction',
            old_name='pinned',
            new_name='hasPinned',
        ),
    ]
