# Generated by Django 5.1.5 on 2025-03-20 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0002_progresstracker_contents_completed_and_more'),
       
    ]

    operations = [
    ]
