# Generated by Django 5.1.5 on 2025-03-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0004_rename_pinned_usermoduleinteraction_haspinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_token',
            field=models.TextField(default=''),
        ),
    ]
