# Generated by Django 5.1.5 on 2025-03-05 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0004_alter_task_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='quiz_type',
            field=models.CharField(choices=[('flashcard', 'Flashcard Quiz'), ('statement_sequence', 'Statement Sequence Quiz'), ('text_input', 'Text Input Quiz'), ('question_answer_form', 'Question Answer Form'), ('matching_questions', 'Matching Questions Quiz')], default='text_input', max_length=30),
        ),
        migrations.CreateModel(
            name='MatchingQuestionQuiz',
            fields=[
                ('contentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_author_contents', to=settings.AUTH_USER_MODEL)),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_contents', to='returnToWork.module')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
