# Generated by Django 5.1.5 on 2025-04-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0005_audioclip_order_index_document_order_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inlinepicture',
            name='author',
        ),
        migrations.RemoveField(
            model_name='inlinepicture',
            name='moduleID',
        ),
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.RemoveField(
            model_name='video',
            name='moduleID',
        ),
        migrations.DeleteModel(
            name='InfoSheet',
        ),
        migrations.DeleteModel(
            name='InlinePicture',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
