# Generated by Django 5.1.5 on 2025-03-08 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0005_task_quiz_type_quizquestion_userresponse'),
        ('returnToWork', '0006_alter_task_quiz_type'),
    ]

    operations = [
    ]
