# Generated by Django 5.1.5 on 2025-03-25 01:52

import returnToWork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0007_remove_document_documents_document_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioclip',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='audioclip',
            name='user_response',
        ),
        migrations.AddField(
            model_name='audioclip',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioclip',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioclip',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audioclip',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audioclip',
            name='audio_file',
            field=models.FileField(upload_to=returnToWork.models.audio_file_path),
        ),
    ]
