# Generated by Django 5.1.5 on 2025-03-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0009_conversation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='lastMessage',
            field=models.TextField(default=''),
        ),
    ]
