# Generated by Django 5.1.5 on 2025-03-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnToWork', '0010_conversation_lastmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to='message-files/'),
        ),
    ]
