name: Django React CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check for Missing Migrations
      run: |
        python manage.py makemigrations --check --dry-run
        
    - name: Run Migrations
      run: |
        python manage.py migrate returnToWork
        
    - name: Run Django Tests
      run: |
        python manage.py test returnToWork.tests --noinput --parallel
        
    - name: Run Django Linting
      run: |
        pip install flake8
        flake8 returnToWork/

  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        npm ci
        
    - name: Run ESLint
      run: |
        npm run lint || true
        
    # - name: Run Tests
    #   run: |
    #     npm test -- --passWithNoTests
        
    - name: Build
      run: |
        npm run build
